# Chilean equities stock data fetching for data visualization
In this project we will use Yahoo's finance API to fetch historical pricing data (CLP Currency) from the biggest chilean company equities that comprise the IPSA Index. 

The IPSA Index, Índice de Precios Selectivo de Acciones, is a stock market index and as such is a profitability indicator, comprising the 30 most traded stocks on the Chilean Stock Exchange.

Once the stock price data is obtained, we will manipulate the information using pandas methods to process the information into dataframes.

Finally we will export the final result to excel ready for use in data visualization tools.

In [1]:
# Import libraries

import yfinance as yf
import pandas as pd

In [2]:
# Import Santiago de Chile (SGO) Stock Exchange Tickers, Company, and Industry from local Excel file
stocks_basic_info = pd.read_excel('SGO Tickers.xlsx', header = None)
tickers = stocks_basic_info[0].to_list()

# Yahoo Finance data download

start_date = '2018-01-01' 
end_date = '2023-10-31'
stock_data = yf.download(tickers, start=start_date, end=end_date)

[*********************100%%**********************]  30 of 30 completed

In [3]:
# DataFrame Manipulation

stock_data = stock_data.stack(level=1).reset_index(level=1, drop=False).reset_index()
stock_data = stock_data.rename({'level_1':'Ticker'}, axis=1)
stock_data

,Date,Ticker,Adj Close,Close,High,Low,Open,Volume
0,2018-01-02,AGUAS-A.SN,272.993683,409.279999,410.000000,406.339996,406.989990,4417525.0
1,2018-01-02,ANDINA-B.SN,2105.668213,3063.500000,3099.000000,3033.000000,3099.000000,218438.0
2,2018-01-02,BCI.SN,27082.822266,34523.191406,34539.074219,33972.820312,33975.203125,53609.0
3,2018-01-02,BSANTANDER.SN,36.027287,48.660000,49.000000,48.189999,48.250000,110458460.0
4,2018-01-02,CAP.SN,4963.488281,8099.100098,8150.000000,7810.100098,7810.100098,345890.0
...,...,...,...,...,...,...,...,...
42984,2023-10-30,RIPLEY.SN,154.419998,154.419998,155.029999,153.000000,153.000000,74440.0
42985,2023-10-30,SMU.SN,156.000000,156.000000,163.990005,156.000000,156.000000,1647918.0
42986,2023-10-30,SONDA.SN,375.880005,375.880005,380.000000,375.000000,378.269989,63804.0
42987,2023-10-30,SQM-B.SN,44698.769531,44700.000000,47750.000000,44547.000000,44700.000000,112807.0
42988,2023-10-30,VAPORES.SN,50.869999,50.869999,52.980000,50.599998,50.869999,10094893.0

In [4]:
# DataFrame Manipulation and merging with company details Data Frame

headers = ['Ticker','Company','Industry']
stocks_basic_info.columns = headers
stocks_basic_info

stock_data = pd.merge(stock_data, stocks_basic_info, on='Ticker', how='left')
stock_data['Exchange'] = 'Santiago Stock Exchange'

stock_data = stock_data.reset_index()
stock_data = stock_data.rename({'index':'FactID'}, axis=1)

# Specify the new order of column positions
new_order = [0, 1, 7, 5, 6, 4, 3, 8, 9, 2, 10, 11]  # Change the order based on your requirements

# Reorder columns based on positions
stock_data = stock_data.iloc[:, new_order]

stock_data

,FactID,Date,Open,High,Low,Close,Adj Close,Volume,Company,Ticker,Industry,Exchange
0,0,2018-01-02,406.989990,410.000000,406.339996,409.279999,272.993683,4417525.0,Aguas Andinas S.A.,AGUAS-A.SN,Utilities - Regulated Water,Santiago Stock Exchange
1,1,2018-01-02,3099.000000,3099.000000,3033.000000,3063.500000,2105.668213,218438.0,Embotelladora Andina S.A.,ANDINA-B.SN,Beverages - Non-Alcoholic,Santiago Stock Exchange
2,2,2018-01-02,33975.203125,34539.074219,33972.820312,34523.191406,27082.822266,53609.0,Banco de Crédito e Inversiones,BCI.SN,Banks - Regional,Santiago Stock Exchange
3,3,2018-01-02,48.250000,49.000000,48.189999,48.660000,36.027287,110458460.0,Banco Santander-Chile,BSANTANDER.SN,Banks - Regional,Santiago Stock Exchange
4,4,2018-01-02,7810.100098,8150.000000,7810.100098,8099.100098,4963.488281,345890.0,CAP S.A.,CAP.SN,Steel,Santiago Stock Exchange
...,...,...,...,...,...,...,...,...,...,...,...,...
42984,42984,2023-10-30,153.000000,155.029999,153.000000,154.419998,154.419998,74440.0,Ripley Corp S.A.,RIPLEY.SN,Department Stores,Santiago Stock Exchange
42985,42985,2023-10-30,156.000000,163.990005,156.000000,156.000000,156.000000,1647918.0,SMU S.A.,SMU.SN,Department Stores,Santiago Stock Exchange
42986,42986,2023-10-30,378.269989,380.000000,375.000000,375.880005,375.880005,63804.0,Sonda S.A.,SONDA.SN,Information Technology Services,Santiago Stock Exchange
42987,42987,2023-10-30,44700.000000,47750.000000,44547.000000,44700.000000,44698.769531,112807.0,Sociedad Química y Minera de Chile S.A.,SQM-B.SN,Specialty Chemicals,Santiago Stock Exchange
42988,42988,2023-10-30,50.869999,52.980000,50.599998,50.869999,50.869999,10094893.0,Compañía Sud Americana de Vapores S.A.,VAPORES.SN,Marine Shipping,Santiago Stock Exchange

In [5]:
# Exporting file as Excel file for further analysis using data visualization tools

stock_data.to_excel('SGO Stock Data.xlsx', index=False)